### ISSUE TITLE
Emulator fails with large programs

### ISSUE THREAD

**Issue by sragss** [a16z/Lasso#148]
Running a 1024k trace length program gets the following error.
```
thread 'main' panicked at tracer/src/emulator/mmu.rs:489:22:
Unknown memory mapping 5050505.
```

https://github.com/a16z/Lasso/blob/jolt/tracer/src/emulator/mmu.rs#L489

**Comment by sragss** [comment]
Here's another:
```
thread 'main' panicked at tracer/src/emulator/cpu.rs:349:17:
Unknown instruction PC:ffffffff80001940 WORD:0
```

**Comment by ncitron** [comment]
Yeah so it turns out these bugs are cropping up when we run out of space on the stack. This does concern me to a certain extent since I wonder what happens security-wise (can you smash the stack somehow?).

As for the fix, it is pretty easy. We can increase the stack size in the linker [here](https://github.com/a16z/Lasso/blob/jolt/examples/hash/linker.ld#L23) and the tracer should continue functioning.

**Comment by delehef** [comment]
I encounter the same issue, but it looks like the mentioned `linker.ld` file does not exist at the same place as aforementioned. Where should one perform the modification now?

**Comment by ncitron** [comment]
We now support modifying the stack and program size values directly from the macro. See an example in our [troubleshooting guide](https://jolt.a16zcrypto.com/usage/troubleshooting.html).
